<a href="https://colab.research.google.com/github/Jeevith252/MACHINE-LEARNING-/blob/main/logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import warnings

warnings.filterwarnings('ignore')

In [43]:
df = sns.load_dataset("titanic")

In [44]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [45]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [47]:
df.drop(["deck" , "embark_town" , "alive" , "class" , "who" , "adult_male"] ,axis = 1 , inplace=True)

In [48]:
df.isnull().sum()

survived      0
pclass        0
sex           0
age         177
sibsp         0
parch         0
fare          0
embarked      2
alone         0
dtype: int64

In [49]:
df['age'].fillna(df['age'].mean() , inplace = True)

In [50]:
df['embarked'].fillna(df["embarked"].mode() , inplace = True)

In [51]:
df.isnull().sum()

survived    0
pclass      0
sex         0
age         0
sibsp       0
parch       0
fare        0
embarked    2
alone       0
dtype: int64

In [52]:
df.dropna(subset = ["embarked"] , inplace = True , axis = 0)

In [53]:
df.isnull().sum()

survived    0
pclass      0
sex         0
age         0
sibsp       0
parch       0
fare        0
embarked    0
alone       0
dtype: int64

In [54]:
df.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0         0       3    male  22.0      1      0   7.2500        S  False
1         1       1  female  38.0      1      0  71.2833        C  False
2         1       3  female  26.0      0      0   7.9250        S   True
3         1       1  female  35.0      1      0  53.1000        S  False
4         0       3    male  35.0      0      0   8.0500        S   True

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  889 non-null    int64
 1   pclass    889 non-null    int64
 2   sex       889 non-null    object
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64
 5   parch     889 non-null    int64
 6   fare      889 non-null    float64
 7   embarked  889 non-null    object
 8   alone     889 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 63.4+ KB

In [56]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [57]:
df['embarked'].value_counts()

embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [58]:
columns = ["sex" ,"embarked", "alone"]
for col in columns:
    df[col] = encoder.fit_transform(df[col])

In [59]:
df.head()

   survived  pclass  sex   age  sibsp  parch     fare  embarked  alone
0         0       3    1  22.0      1      0   7.2500         2      0
1         1       1    0  38.0      1      0  71.2833         0      0
2         1       3    0  26.0      0      0   7.9250         2      1
3         1       1    0  35.0      1      0  53.1000         2      0
4         0       3    1  35.0      0      0   8.0500         2      1

In [60]:
df = df.astype(int)

In [61]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [62]:
for col in df.columns:
  print("========================================")
  print(df[col].value_counts())
  print("========================================")

========================================
survived
0    549
1    340
Name: count, dtype: int64
========================================
========================================
pclass
3    491
1    214
2    184
Name: count, dtype: int64
========================================
========================================
sex
1    577
0    312
Name: count, dtype: int64
========================================
========================================
age
29    197
24     31
22     27
28     27
30     27
     ...
66      1
12      1
53      1
80      1
74      1
Name: count, Length: 71, dtype: int64
========================================
========================================
sibsp
0    606
1    209
2     28
4     18
3     16
8      7
5      5
Name: count, dtype: int64
========================================
========================================
parch
0    676
1    118
2     80
5      5
3      5
4      4
6      1
Name: count, dtype: int64
========================================
========================================
fare
7      213
8       70
26      57
13      50
10      28
      ...
38       1
40       1
221      1
42       1
5        1
Name: count, Length: 90, dtype: int64
========================================
========================================
embarked
2    644
0    168
1     77
Name: count, dtype: int64
========================================
========================================
alone
1    535
0    354
Name: count, dtype: int64
========================================

In [63]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'alone'],
      dtype='object')

In [64]:
column = ['pclass','age','sibsp', 'parch', 'fare','embarked']

In [65]:
df[column] = scaler.fit_transform(df[column])

In [66]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,alone
0,0,0.825209,1,-0.578023,0.431350,-0.474326,-0.496733,0.586840,0
1,1,-1.572211,0,0.655371,0.431350,-0.474326,0.791539,-1.939555,0
2,1,0.825209,0,-0.269675,-0.475199,-0.474326,-0.496733,0.586840,1
3,1,-1.572211,0,0.424109,0.431350,-0.474326,0.429213,0.586840,0
4,0,0.825209,1,0.424109,-0.475199,-0.474326,-0.476604,0.586840,1

# **BUILDING MODEL**

In [67]:
X = df.drop('survived', axis = 1)
y = df['survived']

In [68]:
from sklearn.model_selection import train_test_split

In [69]:
X_train , X_test ,y_train , y_test = train_test_split(X , y , test_size= 0.2 , random_state= 42)

In [70]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train , y_train)

LogisticRegression()

In [71]:
y_pred = model.predict(X_test)

## **CONFUSION MATRIX**

In [73]:
from sklearn.metrics import accuracy_score , confusion_matrix ,classification_report

accuracy_score(y_pred ,y_test)

0.8033707865168539

In [74]:
confusion_matrix(y_pred , y_test)

array([[90, 16],
       [19, 53]])

In [75]:
print(classification_report(y_pred , y_test))

              precision    recall  f1-score   support

           0       0.83      0.85      0.84       106
           1       0.77      0.74      0.75        72

    accuracy                           0.80       178
   macro avg       0.80      0.79      0.79       178
weighted avg       0.80      0.80      0.80       178